name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*.*.*'         # Trigger on tags like v1.0.0, v2.1.0, etc. without -alpha suffix
      - 'v*.*.*-alpha*'  # Trigger on tags like v1.0.0-alpha, v2.1.0-alpha, etc.

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        id: cache-docker-layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build and push Docker image
        env:
          DOCKER_BUILDKIT: 1
          IMAGE_TAG: ${{ github.ref }}
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --file Dockerfile \
            --tag ghcr.io/${{ github.repository }}:${IMAGE_TAG#refs/tags/} \
            --push .
